export const LOADING_LOGIN = 'LOADING_LOGIN'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'

export const LOADING_LOGOUT = 'LOADING_LOGOUT'
export const SUCCESS_LOGOUT = 'SUCCESSLOGOUT_'
export const ERROR_LOGOUT = 'LOGOUT_ERROR'