export const LOADING_LOGIN = 'LOGIN_LOADING'
export const SUCCESS_LOGIN = 'LOGIN_SUCCESS'
export const ERROR_LOGIN = 'LOGIN_ERROR'

export const LOADING LOGOUT_= 'LOGOUT_LOADING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR= 'LOGOUT_ERROR'