export const LOADING_LOGIN = 'LOADING_LOGIN'
export const SUCCESS_LOGIN = ''
export const ERROR_LOGIN = 'LOGIN_ERROR'

export const LOADING_LOGOUT = 'LOGOUT_LOADING'
export const SUCCESS_LOGOUT = 'LOGOUT_SUCCESS'
export const ERROR_LOGOUT = 'LOGOUT_ERROR'