export const LOADING_LOGIN = 'LOGIN_LOADING'
export const SUCCESS_LOGIN = 'LOGIN_SUCCESS'
export const ERROR_LOGIN = 'LOGIN_ERROR'

export const LOADING_LOGOUT= 'LOGOUT_LOADING'
export const SUCCESS_LOGOUT= 'LOGOUT_SUCCESS'
export const ERRORLOGOUT_= 'LOGOUT_ERROR'